export const BankAccountConstants = {
    BANK_ACCOUNT_PENDING: "BANK_ACCOUNT_PENDING",
    BANK_ACCOUNT_REQUEST_SUCCESS: "BANK_ACCOUNT_REQUEST_SUCCESS",
    BANK_ACCOUNT_REQUEST_FAIL: "BANK_ACCOUNT_REQUEST_FAIL",

    GET_REMIND_LIST_PENDING: "GET_BANK_ACCOUNT_REMIND_LIST_PENDING",
    GET_REMIND_LIST_SUCCESS: "GET_BANK_ACCOUNT_REMIND_LIST_SUCCESS",
    GET_REMIND_LIST_ERROR: "GET_BANK_ACCOUNT_REMIND_LIST_ERROR",
}