export const BankAccountConstants = {
    BANK_ACCOUNT_PENDING: "BANK_ACCOUNT_PENDING",
    BANK_ACCOUNT_REQUEST_SUCCESS: "BANK_ACCOUNT_REQUEST_SUCCESS",
    BANK_ACCOUNT_REQUEST_FAIL: "BANK_ACCOUNT_REQUEST_FAIL",

    GET_REMIND_LIST_PENDING: "GET_BANK_ACCOUNT_REMIND_LIST_PENDING",
    GET_REMIND_LIST_SUCCESS: "GET_BANK_ACCOUNT_REMIND_LIST_SUCCESS",
    GET_REMIND_LIST_ERROR: "GET_BANK_ACCOUNT_REMIND_LIST_ERROR",
    
    CREATE_REMIND_LIST_PENDING: "CREATE_REMIND_LIST_PENDING",
    CREATE_REMIND_LIST_SUCCESS: "CREATE_REMIND_LIST_SUCCESS",
    CREATE_REMIND_LIST_ERROR: "CREATE_REMIND_LIST_ERROR",

    DELETE_REMIND_LIST_PENDING: "DELETE_REMIND_LIST_PENDING",
    DELETE_REMIND_LIST_SUCCESS: "DELETE_REMIND_LIST_SUCCESS",
    DELETE_REMIND_LIST_ERROR: "DELETE_REMIND_LIST_ERROR",
    
    UPDATE_REMIND_LIST_PENDING: "UPDATE_REMIND_LIST_PENDING",
    UPDATE_REMIND_LIST_SUCCESS: "UPDATE_REMIND_LIST_SUCCESS",
    UPDATE_REMIND_LIST_ERROR: "UPDATE_REMIND_LIST_ERROR",

    GET_TRANSACTION_HISTORY_PENDING: "GET_TRANSACTION_HISTORY_PENDING",
    GET_TRANSACTION_HISTORY_SUCCESS: "GET_TRANSACTION_HISTORY_SUCCESS",
    GET_TRANSACTION_HISTORY_ERROR: "GET_TRANSACTION_HISTORY_ERROR",
}