export const BankAccountConstants = {
    BANK_ACCOUNT_PENDING: "BANK_ACCOUNT_PENDING",
    BANK_ACCOUNT_REQUEST_SUCCESS: "BANK_ACCOUNT_REQUEST_SUCCESS",
    BANK_ACCOUNT_REQUEST_FAIL: "BANK_ACCOUNT_REQUEST_FAIL"
}