export const TransferConstants = {
    TRANSFER_PENDING: "TRANSFER_PENDING",
    TRANSFER_SUCCESS: "TRANSFER_SUCCESS",
    TRANSFER_ERROR: "TRANSFER_ERROR",

    OTP_PENDING: "OTP_PENDING",
    OTP_SUCCESS: "OTP_SUCCESS",
    OTP_ERROR: "OTP_ERROR",
}