export const TransferConstants = {
    TRANSFER_LOCAL_PENDING: "TRANSFER_PENDING",
    TRANSFER_LOCAL_SUCCESS: "TRANSFER_SUCCESS",
    TRANSFER_LOCAL_ERROR: "TRANSFER_ERROR",

    OTP_PENDING: "OTP_PENDING",
    OTP_SUCCESS: "OTP_SUCCESS",
    OTP_ERROR: "OTP_ERROR",

    FIND_RECEIVER_PENDING: "FIND_RECEIVER_PENDING",
    FIND_RECEIVER_SUCCESS: "FIND_RECEIVER_SUCCESS",
    FIND_RECEIVER_ERROR: "FIND_RECEIVER_ERROR",

    GET_REMIND_LIST_PENDING: "GET_REMIND_LIST_PENDING",
    GET_REMIND_LIST_SUCCESS: "GET_REMIND_LIST_SUCCESS",
    GET_REMIND_LIST_ERROR: "GET_REMIND_LIST_ERROR",

    // TRANSFER_LOCAL_PENDING: "TRANSFER_LOCAL_PENDING",
    // TRANSFER_LOCAL_SUCCESS: "TRANSFER_LOCAL_SUCCESS",
    // TRANSFER_LOCAL_ERROR: "TRANSFER_LOCAL_ERROR",

}