export const EmpConstants = {

    LOGIN_REQUEST : 'LOGIN_EMP_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_EMP_SUCCESS',
    LOGIN_ERROR : 'LOGIN_EMP_ERROR',
    
    LOGOUT : "LOGOUT_EMP",

    ADD_CUSTOMER_PENDING: 'ADD_CUSTOMER_PENDING',
    ADD_CUSTOMER_SUCCESS: 'ADD_CUSTOMER_SUCCESS',
    ADD_CUSTOMER_ERROR: 'ADD_CUSTOMER_ERROR',
}