image: docker:latest
services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker login -u "khuedoan" -p "$DOCKER_PASSWORD"

build:
  stage: build
  script:
    - docker build -t khuedoan/node-kubernetes nodejs
    - docker push khuedoan/node-kubernetes
  only:
    - master

.gcloud: &gcloud
  - echo $GCLOUD_SERVICE_KEY | base64 --decode -i > ~/gcloud-service-key.json
  - gcloud auth activate-service-account --key-file ~/gcloud-service-key.json
  - gcloud --quiet container clusters get-credentials $CLOUDSDK_CONTAINER_CLUSTER

.prod_deploy: &prod_deploy
  image: google/cloud-sdk
  stage: deploy
  environment: production
  before_script: *gcloud
  script:
    - kubectl apply -f kubernetes

auto-deploy-master:
  <<: *prod_deploy
  only:
    - master
