version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: "./mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "banking"
      MYSQL_ROOT_PASSWORD: "cantexitvim"
  nodejs:
    container_name: "nodejs"
    build: "./nodejs"
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    working_dir: "/usr/src/backend-banking"
    depends_on:
      - "mariadb"
