version: "3"

services:
  mariadb:
    container_name: "mariadb"
    build: "./mariadb"
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "banking"
      MYSQL_ROOT_PASSWORD: "cantexitvim"
  nodejs:
    container_name: "nodejs"
    build:
      context: "./"
      dockerfile: "./nodejs/Dockerfile"
    environment:
      - PORT=80
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./backend-banking:/usr/src/backend-banking"
      - "/usr/src/backend-banking/node_modules"
    working_dir: "/usr/src/backend-banking"
    depends_on:
      - "mariadb"
