apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: nodejs
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: nodejs
        imagePullPolicy: ""
        name: nodejs
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        volumeMounts:
        - mountPath: /usr/src/backend-banking
          name: nodejs-claim0
        - mountPath: /usr/src/backend-banking/node_modules
          name: nodejs-claim1
        workingDir: /usr/src/backend-banking
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: nodejs-claim0
        persistentVolumeClaim:
          claimName: nodejs-claim0
      - name: nodejs-claim1
        persistentVolumeClaim:
          claimName: nodejs-claim1
status: {}
