export const UserConstants = {

    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',

    FORGOT_PASSWORD_PENDING: 'FORGOT_PASSWORD_PENDING',
    FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGOT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',

    VERIFY_OTP_PENDING: 'VERIFY_OTP_PENDING',
    VERIFY_OTP_SUCCESS: 'VERIFY_OTP_SUCCESS',
    VERIFY_OTP_ERROR: 'VERIFY_OTP_ERROR',

    CHANGE_PASSWORD_PENDING: 'CHANGE_PASSWORD_PENDING',
    CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',
    CHANGE_PASSWORD_ERROR: 'CHANGE_PASSWORD_ERROR',

    LOGOUT : "LOGOUT"
}