export const UserConstants = {

    LOGIN_REQUEST : 'LOGIN_REQUEST',
    LOGIN_SUCCESS : 'LOGIN_SUCCESS',
    LOGIN_ERROR : 'LOGIN_ERROR',

    FORGT_PASSWORD_PENDING: 'FORGOT_PASSWORD_PENDING',
    FORGT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
    FORGT_PASSWORD_ERROR: 'FORGOT_PASSWORD_ERROR',

    LOGOUT : "LOGOUT"
}